### ISSUE TITLE
1.0.10 Missing js build

### ISSUE THREAD

**Issue by bobmccracken** [actions/http-client#43] opened 2021-03-25 01:59 UTC
I'm using @actions/github in my CI process, but it's failing with this stacktrace:

```
Error: Cannot find module '/home/runner/work/inc-web-ordering-v2/inc-web-ordering-v2/node_modules/@actions/http-client/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/inc-web-ordering-v2/inc-web-ordering-v2/node_modules/@actions/github/lib/internal/utils.js:23:33)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/work/inc-web-ordering-v2/inc-web-ordering-v2/node_modules/@actions/http-client/package.json',
  requestPath: '@actions/http-client'
```

I noticed this issue was opened recently over at @actions/toolkit: https://github.com/actions/toolkit/issues/747

Is the latest release missing compiled js?

**Comment by ilya144** [comment] 2021-03-25 08:26
same problem with the @actions/github install

**Comment by ThomasFlorelli** [comment] 2021-03-25 09:54
Hello! Any ETA on this? Just to know if we need to find a workaround or wait as it is blocking deployments for us and I guess a bunch of other people

**Comment by ilya144** [comment] 2021-03-25 10:36
Is it possible to move http-client into peerDependencies?

**Comment by esbena** [comment] 2021-03-25 13:05
This seems to be a duplicate of the now-resolved https://github.com/actions/http-client/issues/44.

**Closed** 2021-03-25 14:33 UTC
